version: "3"
services:
  postgres:
    image: postgres:14
    container_name: db_container
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db/.pgdata:/var/lib/postgresql/data/
    env_file: .env
    healthcheck:
      test: "echo 'SELECT 1' | PGPASSWORD=$POSTGRES_PASSWORD psql --host $$HOSTNAME --user $POSTGRES_USER $POSTGRES_DB"
      interval: 1m
      timeout: 10s
      retries: 3

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    ports:
      - "${PGADMIN_PORT}:80"
    env_file: .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  minio:
    image: minio/minio:RELEASE.2024-06-22T05-26-45Z.fips
    container_name: s3_container
    command: server --console-address ":${MINIO_CONSOLE_PORT}" /data/
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    env_file:
      - .env
    volumes:
      - ./minio-storage:/data
    healthcheck:
      test: "curl --fail http://localhost:$$MINIO_PORT/minio/health/live"
      interval: 30s
      timeout: 20s
      retries: 3


  public-service: &public-service
    build: .
    env_file: .env
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
      - minio
    container_name: public_service
    ports:
      - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    command: /app/start.sh "${WEB_APP_PORT}" src.public.app:app
    healthcheck:
      test: "curl --fail http://localhost:$$WEB_APP_PORT/$$WEB_APP_HEALTHCHECK_PATH || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3

  private-service:
    <<: *public-service
    container_name: private_service
    ports:
      - "${WEB_PRIVATE_APP_PORT}:${WEB_PRIVATE_APP_PORT}"
    command: /app/start.sh "${WEB_PRIVATE_APP_PORT}" src.private.app:app
    healthcheck:
      test: "curl --fail http://localhost:$$WEB_PRIVATE_APP_PORT/$$WEB_APP_HEALTHCHECK_PATH || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3


