version: "3"
services:
  postgres:
    image: postgres:14
    container_name: db_container
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./db/.pgdata:/var/lib/postgresql/data/
      - .:/app
    env_file: .env
    healthcheck:
      test: "echo 'SELECT 1' | PGPASSWORD=$POSTGRES_PASSWORD psql --host $$HOSTNAME --user $POSTGRES_USER $POSTGRES_DB"
      interval: 1m
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:latest
    container_name: s3_container
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  fastapi:
    build: .
    container_name: web_service_container
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
      - minio
    healthcheck:
      test: "curl --fail http://localhost:$$WEB_APP_PORT/$$WEB_APP_HEALTHCHECK_PATH || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3


