"""add etag

Revision ID: 42dafb0cad6c
Revises: 6f67c0dcd44e
Create Date: 2024-06-23 11:42:43.836570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42dafb0cad6c'
down_revision: Union[str, None] = '6f67c0dcd44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('etag', sa.String(), nullable=True))
    op.drop_index('ix_memes_url', table_name='memes')
    op.create_index(op.f('ix_memes_etag'), 'memes', ['etag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memes_etag'), table_name='memes')
    op.create_index('ix_memes_url', 'memes', ['url'], unique=False)
    op.drop_column('memes', 'etag')
    # ### end Alembic commands ###
