"""init

Revision ID: 6f67c0dcd44e
Revises: 
Create Date: 2024-06-22 14:02:16.236637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f67c0dcd44e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memes_id'), 'memes', ['id'], unique=False)
    op.create_index(op.f('ix_memes_title'), 'memes', ['title'], unique=False)
    op.create_index(op.f('ix_memes_url'), 'memes', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memes_url'), table_name='memes')
    op.drop_index(op.f('ix_memes_title'), table_name='memes')
    op.drop_index(op.f('ix_memes_id'), table_name='memes')
    op.drop_table('memes')
    # ### end Alembic commands ###
